### ISSUE TITLE
Not possible to run tests in IntelliJ in debug mode

### ISSUE THREAD

**Issue by st1p3kolovrat** [prashant-ramcharan/courgette-jvm-selenium#4]
When user initiates tests in debug mode 
And sets breakpoints in java step method files
Then tests are runned 
And Courgette did not recognize that debug mode should be stopped on breakpoints 

It behaves as there are no breakpoints. 

This makes it difficult to write tests, without ability to be able to run tests in debug mode and see which method that you implemented does what. 

Can debug somehow be added?

**Comment by prashant-ramcharan** [comment]
Hi @StipeKolovrat 

You can and should debug your tests as you would any Cucumber-JVM test by using the IntelliJ cucumber plugin.

You cannot use the Courgette runner to debug tests because each test is run in a separate JVM.

I suggest you use the IntelliJ cucumber plugin to debug a test and use Courgette to execute your tests in parallel.

Hope this helps.

**Comment by st1p3kolovrat** [comment]
Hi, 

Now I am able to debug RunWith(Cucumber) 

Issue before I had is, I was using deprecated cucumber import. All good. Thanks
